package com.wifi.model.model;

import java.util.Date;

/**
 * generated by MGB(Mybatis Generator), 小心修改
 * 
 * table name : search_people
 *
 * @create time : 2019-09-22
 */
public class SearchPeople {
    /**
     * 主键
     * column : search_people.id
     */
    private Integer id;

    /**
     * app_id
     * column : search_people.app_id
     */
    private String appId;

    /**
     * UHID
     * column : search_people.uhid
     */
    private String uhid;

    /**
     * 姓名
     * column : search_people.name
     */
    private String name;

    /**
     * 展示标题
     * column : search_people.display_title
     */
    private String displayTitle;

    /**
     * 性别
     * column : search_people.gender
     */
    private String gender;

    /**
     * 详细地址
     * column : search_people.detail_address
     */
    private String detailAddress;

    /**
     * 年龄
     * column : search_people.age
     */
    private Integer age;

    /**
     * 情况介绍
     * column : search_people.description
     */
    private String description;

    /**
     * 丢失时间
     * column : search_people.lost_time
     */
    private Date lostTime;

    /**
     * 丢失地点
     * column : search_people.lost_address
     */
    private String lostAddress;

    /**
     * 丢失原因
     * column : search_people.lost_reason
     */
    private String lostReason;

    /**
     * 发现时间
     * column : search_people.find_time
     */
    private Date findTime;

    /**
     * 发现地点
     * column : search_people.find_address
     */
    private String findAddress;

    /**
     * 救助单位
     * column : search_people.rescue_unit
     */
    private String rescueUnit;

    /**
     * 联系人1
     * column : search_people.contact1
     */
    private String contact1;

    /**
     * 联系人1电话
     * column : search_people.telephone1
     */
    private String telephone1;

    /**
     * 联系人2
     * column : search_people.contact2
     */
    private String contact2;

    /**
     * 联系人2电话
     * column : search_people.telephone2
     */
    private String telephone2;

    /**
     * 是否已经报警，报警1，未报警0
     * column : search_people.call_police
     */
    private Integer callPolice;

    /**
     * 审核历史
     * column : search_people.examine_history
     */
    private String examineHistory;

    /**
     * 推送时间
     * column : search_people.push_time
     */
    private Date pushTime;

    /**
     * 推送间隔
     * column : search_people.push_interval
     */
    private Integer pushInterval;

    /**
     * 推送次数
     * column : search_people.push_times
     */
    private Integer pushTimes;

    /**
     * 状态：等待审核0, 审核不通过1, 正在寻人2, 已停止3
     * column : search_people.status
     */
    private Integer status;

    /**
     * 回访记录
     * column : search_people.revisit_record
     */
    private String revisitRecord;

    /**
     * 停止
     * column : search_people.stop
     */
    private String stop;

    /**
     * 创建时间
     * column : search_people.create_time
     */
    private Date createTime;

    /**
     * 修改时间
     * column : search_people.update_time
     */
    private Date updateTime;

    /**
     * 寻人1，寻亲2
     * column : search_people.search_type
     */
    private Integer searchType;

    /**
     * 备注
     * column : search_people.remark
     */
    private String remark;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getAppId() {
        return appId;
    }

    public void setAppId(String appId) {
        this.appId = appId;
    }

    public String getUhid() {
        return uhid;
    }

    public void setUhid(String uhid) {
        this.uhid = uhid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDisplayTitle() {
        return displayTitle;
    }

    public void setDisplayTitle(String displayTitle) {
        this.displayTitle = displayTitle;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getDetailAddress() {
        return detailAddress;
    }

    public void setDetailAddress(String detailAddress) {
        this.detailAddress = detailAddress;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Date getLostTime() {
        return lostTime;
    }

    public void setLostTime(Date lostTime) {
        this.lostTime = lostTime;
    }

    public String getLostAddress() {
        return lostAddress;
    }

    public void setLostAddress(String lostAddress) {
        this.lostAddress = lostAddress;
    }

    public String getLostReason() {
        return lostReason;
    }

    public void setLostReason(String lostReason) {
        this.lostReason = lostReason;
    }

    public Date getFindTime() {
        return findTime;
    }

    public void setFindTime(Date findTime) {
        this.findTime = findTime;
    }

    public String getFindAddress() {
        return findAddress;
    }

    public void setFindAddress(String findAddress) {
        this.findAddress = findAddress;
    }

    public String getRescueUnit() {
        return rescueUnit;
    }

    public void setRescueUnit(String rescueUnit) {
        this.rescueUnit = rescueUnit;
    }

    public String getContact1() {
        return contact1;
    }

    public void setContact1(String contact1) {
        this.contact1 = contact1;
    }

    public String getTelephone1() {
        return telephone1;
    }

    public void setTelephone1(String telephone1) {
        this.telephone1 = telephone1;
    }

    public String getContact2() {
        return contact2;
    }

    public void setContact2(String contact2) {
        this.contact2 = contact2;
    }

    public String getTelephone2() {
        return telephone2;
    }

    public void setTelephone2(String telephone2) {
        this.telephone2 = telephone2;
    }

    public Integer getCallPolice() {
        return callPolice;
    }

    public void setCallPolice(Integer callPolice) {
        this.callPolice = callPolice;
    }

    public String getExamineHistory() {
        return examineHistory;
    }

    public void setExamineHistory(String examineHistory) {
        this.examineHistory = examineHistory;
    }

    public Date getPushTime() {
        return pushTime;
    }

    public void setPushTime(Date pushTime) {
        this.pushTime = pushTime;
    }

    public Integer getPushInterval() {
        return pushInterval;
    }

    public void setPushInterval(Integer pushInterval) {
        this.pushInterval = pushInterval;
    }

    public Integer getPushTimes() {
        return pushTimes;
    }

    public void setPushTimes(Integer pushTimes) {
        this.pushTimes = pushTimes;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getRevisitRecord() {
        return revisitRecord;
    }

    public void setRevisitRecord(String revisitRecord) {
        this.revisitRecord = revisitRecord;
    }

    public String getStop() {
        return stop;
    }

    public void setStop(String stop) {
        this.stop = stop;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Integer getSearchType() {
        return searchType;
    }

    public void setSearchType(Integer searchType) {
        this.searchType = searchType;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }
}